<a href="https://colab.research.google.com/github/sagarsitap596/gcolab_python/blob/master/Manipulating_Data_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulating Data using NumPy

## Explainer Video

In [0]:
from IPython.display import HTML

HTML('<iframe src="https://player.vimeo.com/video/278480086" width="800" height="600" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')


![caption](../images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. Let's along with the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [0]:
import numpy as np
np.array

?np


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [0]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

### Instructions
* Create a list of number's as `[10,20,30]` and save it as `my_list`
* Convert the list into an array using `np.array()`

In [0]:
import numpy as np

my_list = list(range(10,40,10))
print(np.array(range(10,40,10)))
print(np.asarray(my_list))
print(np.asarray(range(10,40,10)))

aa=np.array([[1,2,3]])
aa.shape

[10 20 30]
[10 20 30]
[10 20 30]


(1, 3)

### Instructions
* Create a list of list as `[[5, 10, 15], [20, 25, 30], [35, 40, 45]]` and save it as `list_of_lists `
* Convert the list of list into an array using `np.array()` and print it.
* Check the `type()` of the array.

In [0]:
list_of_lists = list(range(5,50,5))
my_array = np.array(list_of_lists)
my_array
# print(my_array.reshape(3,3))
print(my_array.resize(3,3))
my_array

print(my_array)
print(my_array.shape)
print(my_array.ndim)
print(my_array[0:1,])
print(my_array.nbytes) # total size (elements * dtype size of each )
print(type(my_array.dtype))

None
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3, 3)
2
[[ 5 10 15]]
72
<class 'numpy.dtype'>


In [0]:
# reshape vs resize
# reshape return bew array and doesnt chnages original array.
# resize changes original array and return None
my_array = np.array(range(5,50,5))
my_array
# print(my_array.reshape(3,3))
print(my_array.resize(3,3))
my_array

An example of how does n-dimensional looks

## Types

![NumPy Array Types](../images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.ndim***
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.size***
the total number of elements of the array. This is equal to the product of the elements of shape.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* **string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [0]:
my_vector1=np.ndarray([[10, 20, 30]])
print(my_vector1.dtype)
print(my_vector1.shape)


TypeError: ignored

In [0]:
vector1=np.array([10, 20, 30]) 
vector2=np.ndarray([10, 20, 30]) 

print(vector1)
print("="*30)
print(vector2)

[10 20 30]
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />

### Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]]. Print the dtype and shape. 
***

In [0]:
matx=np.array([[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]])
matx

array([[ 5.3, 10.2, 15.1],
       [20.4, 25.3, 30.9],
       [35.4, 40.1, 45.6]])

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Indexing and Selection
***
Basic slicing extends Python's basic concept of slicing to N dimensions. Basic slicing occurs when obj is a :class: slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. :const:Ellipsis and :const:newaxis objects can be interspersed with these as well. In order to remain backward compatible with a common usage in Numeric, basic slicing is also initiated if the selection object is any non-ndarray sequence (such as a :class:list) containing :class:slice objects.

Let us look at creating an array with numpy and indexing and selection follows from what we have learnt in python

### Instructions
* Create an array from `0` to `9` using `np.arange()` and save it as `arr`
* Print the element at index `5`
* Print the elements from `1` to `9` with an interval of `2`

In [0]:
# indexing one dimensional array
a1=np.arange(0,10)

# get the element at index 5
print(a1[5])

#Get values in a range
print(a1[0::2])



5
[0 2 4 6 8]


### Instructions
* Create a two dimensional array from `1` to `9` and save it as `arr` and print it.
* Print 1st row
* Print the value of 2nd row and 2nd column
* Print the value of 0th row and 2nd column

In [0]:
# indexing two dimensional array
arr=np.array(range(1,10)).reshape(3,3)
print(arr[0:1,])
print(arr[1,2])
print(arr[0,2])

[[1 2 3]]
6
3


# Analyzing the Weather using NumPy

<center><img src="../images/weather.jpg" alt="Weather" style="width: 350px;"/></center>
Now it's time to use some them to learn data manipulation by analyzing a weather data set. As they say

We'll be working with **weather_small_2012.csv**, which contains weather data for each hour in 2012.
Since weather_small_2012.csv is a csv file, rows are separated by line breaks, and columns are
separated by commas:

```
Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27
```

**To read csv file, we use:**

    numpy.genfromtxt(fileName, delimeter=",")

### Instructions
* `weather` variable  is already defined for you with the dataset path
* Print the type of the dataset using `.dtype`
* Also print the `weather` dataset and have a look at it

Many items in this dataset are nan.

* The entire first row is nan – headers are String.
* Some of the numbers are written like 1.98600000e+03.

The data type of weather is float. Because all of the values in a NumPy array have to have the same
data type, NumPy attempted to convert all of the columns to floats when they were read in.

In [0]:
import numpy as np
# read csv file
weather = np.genfromtxt("/content/weather_small_2012.csv", delimiter=",",skip_header=1)
print(weather)
print(weather.shape)
print(weather.ndim)
print(weather.dtype)

[[   nan  -1.8   -3.9  ...   4.     8.   101.24]
 [   nan  -1.8   -3.7  ...   4.     8.   101.24]
 [   nan  -1.8   -3.4  ...   7.     4.   101.26]
 ...
 [   nan  -0.5   -1.5  ...  28.     4.8   99.95]
 [   nan  -0.2   -1.8  ...  28.     9.7   99.91]
 [   nan   0.    -2.1  ...  30.    11.3   99.89]]
(8784, 7)
2
float64


**Reading In The Data Properly**

***
To read weather_small_2012.csv file properly we will have to use correct data type and skip the header.
* genfromtxt() default dtype is float, it converts non-numeric value to nan (not a number)
* To avoid nan, we read values as |S20 (String of length 20) 

### Instructions
* Read the Weather data using `np.genfromtxt()` by passing parameters as `path of the dataset`,`dtype='|S20'`, `skip_header=1`, `delimiter=","`
* Print the value of first index of the dataset

In [0]:
weather= np.genfromtxt("/content/weather_small_2012.csv", delimiter=",",skip_header=1,dtype="|S20")
print(weather.dtype)
print(weather.shape)

|S20
(8784, 7)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Instructions
* Create an array of temperature and convert it into float16 using `.astype(np.float16)` and save it as `temperatures`.
* Create an array of dew point temperature and convert it into float16 using `.astype(np.float16)` and save it as `dew_point_temperatures`.


In [0]:
# Create an array of temperatures from the data set

temperatures = weather[:,1].astype(np.float16)
print(temperature)

dew_point_temperatures=weather[:,2].astype(np.float16)
print(dew_point_temperatures)

[-1.8 -1.8 -1.8 ... -0.5 -0.2  0. ]
[-3.9 -3.7 -3.4 ... -1.5 -1.8 -2.1]


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

# Operations with NumPy arrays
***
NumPy provides a lot of built-in functionality for working with arrays.
**The important concepts to remember are**
- Any operation with a scalar number or a scalar function will cause that operation being computed for each element
- Any operation with two **compatible** (eg.: same shape) arrays will cause one-to-one element computations

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (1/2)
***
### Vector Arithmetic
- All operations between arrays are **element-wise**
- This means that if you multiply two 2d vectors, it will **NOT** perform matrix multiplication

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (2/2)
***
### Scalar Arithmetic
- Any operation of an array with a scalar will result in **element-wise** computation of that operation
- For example **`my_array + 2`** is the same as adding 2 to each element of array

### Instructions
* Calculate the Temperatures from the weather dataset in Farenheit

### Addition

### Instructions
* Print Vector Addition of `temperatures` and `dew_point_temperatures`
* Print Scalar Addition of `temperatures` + 100

In [0]:
# Total temperature

# Vector Addition
print(np.add(temperatures,dew_point_temperatures))

# Scalar Addition
print(temperatures+100)

[-5.7 -5.5 -5.2 ... -2.  -2.  -2.1]
[ 98.2  98.2  98.2 ...  99.5  99.8 100. ]


### Division
### Instructions
* Create an array from `1` to `10` using `np.arange()` and passing parameter as `dtype=np.float16` and reshape it in 3 X 3 matrix and save it as `array1`
* Create an array from `100` to `109` using `np.arange()` and passing parameter as `dtype=np.float16` and reshape it in 3 X 3 matrix and save it as `array2`
* Perform Vector Division by dividing `array2` by `array1`
* Perform Scalar Division by dividing `array2` by `3`

In [0]:
array1=np.arange(1,10,dtype=np.float16).reshape(3,3)
array2=np.arange(100,109,dtype=np.float16).reshape(3,3)

# Vector Division
print(array2 /array1)
# Scalar Division
print(array2 / 3)


[[100.     50.5    34.   ]
 [ 25.75   20.8    17.5  ]
 [ 15.14   13.375  12.   ]]
[[33.34 33.66 34.  ]
 [34.34 34.66 35.  ]
 [35.34 35.66 36.  ]]


## Comparison

Comparing two numpy arrays for equality, element-wise

### Instructions
* Find `temperatures` that are above `0` degree celcius and save it as `greater_than_0`
* Print `temperatures` and `greater_than_0`
* Print type of `greater_than_0` using `type()`
* Print type of `greater_than_0` using `.dtype`

In [0]:
# Find those temperatures that are above 0 degrees Celcius
greater_than_0 = temperatures[temperatures > 0]
print(greater_than_0)
print(type(greater_than_0))
print(greater_than_0.dtype)


[0.2 0.8 1.8 ... 0.6 0.1 0.2]
<class 'numpy.ndarray'>
float16


### Instructions
* Create 3 X 3 matrix using `1` to `9` numbers and save it as `arr`
* Check the condition for `2` or `5` in `arr` and save it as `two_or_five` and print it.

In [188]:
# multiple conditions
arr = np.arange(1,10).reshape(3,3)
two_or_five = (arr == 2 | arr == 5) 
print(two_or_five)


ValueError: ignored

<img src="../images/icon/Technical-Stuff.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Aggregation 
***
* **`sum()`:** Computes the sum of all the elements in a vector, or the sum along a dimension in a matrix.
* **`mean()`:** Computes the average of all the elements in a vector, or the average along a dimension in a matrix.
* **`max()`/`min()`:** Identifies the maximum/minimum value among all the elements in a vector, or along a dimension in a matrix.
* **`argmax()`/`argmin()`:** Returns the index of maximum/minimum element.

### Instructions
* Find Max temperature using `.max()` on `temperatures`
* Find Min temperature using `.min()` on `temperatures`
* Find Mean temperature using `.mean()` on `temperatures`
* Find index of Max temperature using `.argmax()` on `temperatures`
* Find index of Min temperature using `.argmin()` on `temperatures`

In [187]:
# Find max, min, mean temperature
print(np.max(temperatures))
print(np.min(temperatures))
print(np.mean(temperatures))
print(np.argmax(temperatures))
print(np.argmin(temperatures))

# Find index of max/min temperature


33.0
-23.3
8.8
4143
344


## Quiz
1. Which of these best describes an array?

```python
a) A data structure that shows a hierarchical behavior
b) Container of objects of similar types
c) Container of objects of mixed types
d) All of the mentioned
```
2. What gets printed?

```python
import numpy as np
a = np.array([1,2,3,5,8])
print (a.ndim)
a) 0
b) 1 
c) 2
d) 3
e) 5
```
3. What is the output of the follwing code snippet?

```python
import numpy as np
a = np.arange(12).reshape(3,4)
print(a[2,1])
```

# Further Reading
***
- Python Official Documentation: https://docs.python.org/
- NumPy documentation: http://www.numpy.org/

# Thank You
***
### Coming up next...

- Data Wrangling with Pandas

For more queries - Reach out to academics@greyatom.com 