<a href="https://colab.research.google.com/github/sagarsitap596/gcolab_python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])

print(a1.size)
print(a1.shape)
print(len(a1))
print(a1[::-1])
print(a1[:,1:])

6
(2, 3)
2
[[4 5 6]
 [1 2 3]]
[[2 3]
 [5 6]]


In [0]:
# 2d array
a1=np.array([[0,1,2,3], [2,3,4]], dtype=object)
print(a1.ndim)

1


In [0]:
a = np.zeros(6)
print(a)
b = np.arange(0,10,2)
print(b)
c=a+b
print(c)

[0. 0. 0. 0. 0. 0.]
[0 2 4 6 8]


ValueError: ignored

In [0]:
a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)
c = a * b
print (c[4])

40


In [0]:
a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
print(a)
b = a + 3
print(b)
print (a[1,2] + b[1,2])

[[3 4 3]
 [4 3 4]]
[[6 7 6]
 [7 6 7]]
11


In [0]:
#Vectorization

greaterThen2 = a1 > 2
print(greaterThen2)
b = a1[greaterThen2]
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]


In [0]:
# Operations
a=np.arange(1,10).reshape((3,3))
b=np.full((3,3),2)

print("="*20)
#Addition
print(a+b)
print(np.add(a,b))

print("="*20)
#Subtraction
print(a-b)
print(np.subtract(a,b))

print("="*20)
#Mjltiplication
print(a*b)
print(np.multiply(a,b))

print("="*20)
#Division
print(a/b)
print(np.divide(a,b))

print("="*20)
# square
square=a**2
print(square)

print("="*20)
# sqrt
print(np.sqrt(b))





[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]]


In [0]:
# Aggregations functions

# axis =0 is column wise
# axis =1 row wise

a=np.arange(1,11).reshape((5,2))

print(np.min(a))
print(np.min(a,axis=0)) # min of all entries in each column. Since there are two columns output is t
print(np.min(a,axis=1))
print("="*20)

print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print("="*20)

print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print("="*20)

print(np.cumsum(a)) # cumulitive sum of all numbers till every index

1
[1 2]
[1 3 5 7 9]
10
[ 9 10]
[ 2  4  6  8 10]
55
[25 30]
[ 3  7 11 15 19]
[ 1  3  6 10 15 21 28 36 45 55]


In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.delete(a,1,0)) # (array,index,axis (0=row, 1=column))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
