<a href="https://colab.research.google.com/github/sagarsitap596/gcolab_python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])

print("Size :",a1.size)
print("Dimensiom :",a1.ndim)
print("Data type",a1.dtype)
print("Size of datatype in bytes",a1.itemsize)
print("Total size in bytes",a1.nbytes)
print("m X n",a1.shape)
print("Length of rows",len(a1))
print(a1[::-1])
print(a1[:,1:])

Size : 6
Dimensiom : 2
Data type int64
Size of datatype in bytes 8
Total size in bytes 48
m X n (2, 3)
Length of rows 2
[[4 5 6]
 [1 2 3]]
[[2 3]
 [5 6]]


In [0]:
# 2d array
a1=np.array([[0,1,2,3], [2,3,4]], dtype=object)
print(a1.ndim)

1


In [0]:
a = np.zeros(6)
print(a)
b = np.arange(0,10,2)
print(b)
c=a+b
print(c)

[0. 0. 0. 0. 0. 0.]
[0 2 4 6 8]


ValueError: ignored

In [0]:
a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)
c = a * b
print (c[4])

40


In [0]:
a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
print(a)
b = a + 3
print(b)
print (a[1,2] + b[1,2])

[[3 4 3]
 [4 3 4]]
[[6 7 6]
 [7 6 7]]
11


In [0]:
#Vectorization

greaterThen2 = a1 > 2
print(greaterThen2)
b = a1[greaterThen2]
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]


In [0]:
# Operations
a=np.arange(1,10).reshape((3,3))
b=np.full((3,3),2)

print("="*20)
#Addition
print(a+b)
print(np.add(a,b))

print("="*20)
#Subtraction
print(a-b)
print(np.subtract(a,b))

print("="*20)
#Mjltiplication
print(a*b)
print(np.multiply(a,b))

print("="*20)
#Division
print(a/b)
print(np.divide(a,b))

print("="*20)
# square
square=a**2
print(square)

print("="*20)
# sqrt
print(np.sqrt(b))





[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]
 [1.41421356 1.41421356 1.41421356]]


In [0]:
# Aggregations functions

# axis =0 is column wise
# axis =1 row wise

a=np.arange(1,11).reshape((5,2))

print(np.min(a))
print(np.min(a,axis=0)) # min of all entries in each column. Since there are two columns output is t
print(np.min(a,axis=1))
print("="*20)

print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print("="*20)

print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print("="*20)

print(np.cumsum(a)) # cumulitive sum of all numbers till every index

1
[1 2]
[1 3 5 7 9]
10
[ 9 10]
[ 2  4  6  8 10]
55
[25 30]
[ 3  7 11 15 19]
[ 1  3  6 10 15 21 28 36 45 55]


In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.delete(a,1,0)) # (array,index,axis (0=row, 1=column))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
a1=np.array([1,2,3])
a2=np.ndarray([1,2,3],dtype=int)
print(a1)
print(a2)

The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

In [0]:
print(np.eye(8, 7, k = 1))
print(np.eye(8, 7, k = -2))
print(np.eye(8, 7, k = -933))
print(np.eye(8, 7))



[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [0]:
N,M=tuple([int(i) for i in input().strip().split(' ')])
print(numpy.eye((N,M)))

https://thispointer.com/find-the-index-of-a-value-in-numpy-array/

Index of element in 1D Numpy array

In [0]:
arr1=np.array([1,2,3,4,5,6,7,5,6,7,8,9],dtype=int)
print(arr1)

index=np.where(arr1==5) 

print(index)

print("Index of 5 is : {}".format(index[0]))
print("first Index of 5 is : {}".format(index[0][0]))




[1 2 3 4 5 6 7 5 6 7 8 9]
(array([4, 7]),)
Index of 5 is : [4 7]
first Index of 5 is : 4


Index of element in 2D Numpy array

In [0]:
arr1=np.array([[1,2,3],[4,5,6],[7,5,5]])
print(arr1)

index=np.where(arr1 == 5)

print(index)

rows_index=index[0]
columns_index=index[1]

coordinates=tuple(zip(rows_index,columns_index))

print(coordinates)

[[1 2 3]
 [4 5 6]
 [7 5 5]]
(array([1, 2, 2]), array([1, 1, 2]))
((1, 1), (2, 1), (2, 2))


In [17]:
# conditions

array1 = np.arange(9).reshape(3,3)
 
print(array1[array1 > 5 and array1 < 8])

ValueError: ignored

In [45]:
#Addition and sum

arr1=np.array([[1,2],[3,4],[1,1]])
arr2=np.array([[11,22],[33,44],[2,2]])
print(np.add(arr1,arr2))
print(np.sum(arr1))

print(np.sum(arr1,axis=0))
print(np.sum(arr1,axis=1))

# broadcasting
print("="*20)
arr1=np.array([[1,2,3]])
print(arr1,arr1.T,sep='\n')
print(np.add(arr1,arr1.T))
print("="*20)


print("="*20)

print(np.add(np.array([[1,2,3],[1,2,3],[1,2,3]]),np.array([[1,2,3],[1,2,3],[1,2,3]])))


[[12 24]
 [36 48]
 [ 3  3]]
12
[5 7]
[3 7 2]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
(1, 3)
(3,)
[[2 4 6]]
[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [49]:
arr1=np.array([1,2,3]).reshape(1,3)
arr2=np.array([1,2,3]).reshape(3,)

print(arr1)
print(arr2)

print(np.add(arr1,arr2))

[[1 2 3]]
[1 2 3]
[[2 4 6]]


In [33]:
# Concatenate
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[11,22,33],[44,55,66]])

print(a1)
print(a2)
print(np.concatenate((a1,a2),axis=0))

print(np.concatenate((a1,a2),axis=1))


[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [44 55 66]]
[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [44 55 66]]
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]


In [0]:
# linspace

In [51]:
print(np.linspace(0,10,10))
print(len(np.linspace(0,10,10)))

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
10
